// bigdict.h / bigdict.cpp — GENERATED by cmu2bigdict.py. Do not edit by hand:
// override a word by adding it to extradict.h, which is searched first.
//
// 30000 words: the most frequent English words (wordfreq ranking) that are in
// CMUdict and NOT already in standardDict.cpp or extradict.h. Pronunciations
// are CMUdict's, converted to SpeakJet codes by a model learned from Sensory's
// hand-tuned dictionary. Sources: CMUdict (BSD), wordfreq (Apache-2.0).
//
// FORMAT. BIGDICT_DATA holds entries back to back:  word bytes, 0, codes, 255.
// BIGDICT_INDEX[i] is the offset of entry i. Entries are sorted by the raw
// bytes of the lowercase word, so a binary search comparing lowercase bytes
// finds them. Every entry is <= 56 codes.

#ifndef BIGDICT_H
#define BIGDICT_H
#include <stdint.h>
extern const uint32_t BIGDICT_COUNT;
extern const uint32_t BIGDICT_INDEX[];
extern const uint8_t  BIGDICT_DATA[];
#endif
